// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keyidafizkanmbeqoclw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleWlkYWZpemthbm1iZXFvY2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mjk3ODIsImV4cCI6MjA3MTEwNTc4Mn0.12RwNK9GnjVcaMeCmhGdH36kJXg0YXHVbypLRXdAE1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});